### ISSUE TITLE
gpt2model训练模型

### ISSUE THREAD

**Issue by hobbszhou** [lzbcs/wxChatBot#4]
up主，gpt2model训练模型可以发一份吗

file gpt2model/config.json not found
[2021-12-12 17:28:59,350] ERROR in app: Exception on /wechat8000 [POST]
Traceback (most recent call last):

**Comment by bird2426** [comment]
链接：https://pan.baidu.com/s/19V2u0VDti3oQEngFEKYgeg 
提取码：1yqz

**Comment by hobbszhou** [comment]
感谢大佬，3q。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lzbcs/wxChatBot] gpt2model训练模型 (Issue #4)





 
链接：https://pan.baidu.com/s/19V2u0VDti3oQEngFEKYgeg
 提取码：1yqz
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hobbszhou** [comment]
up还有个问题。我刚刚用你的模型。但是不管我发什么，都是回 "啊哦，我好像突然傻掉了呢，请问问标神看看他怎么回答吧".





上图是我加了一些打印日志，不管 我发什么问题，他是进了&nbsp;
&nbsp; &nbsp; if reply[0] != AUDIENCE_MARK:
&nbsp; &nbsp; &nbsp; &nbsp; reply = [NO_IDEA]
这个if里面。&nbsp;

------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lzbcs/wxChatBot] gpt2model训练模型 (Issue #4)





 
链接：https://pan.baidu.com/s/19V2u0VDti3oQEngFEKYgeg
 提取码：1yqz
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bird2426** [comment]
不好意思，好像是代码没更新，predict.py的tokenizer另一个同学改过一次，现在应该好了

**Comment by bird2426** [comment]
你可以再pull一下

**Comment by hobbszhou** [comment]
up,我拉的是你main分支的代码，我看只有predict.py一行更新了.现在报错如下:


 r_text= 还是
[2021-12-12 19:23:24,504] ERROR in app: Exception on /wechat8000 [POST]
Traceback (most recent call last):
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/python/gong_zhong_hao/wxChatBot-main/robot/flask.py", line 29, in werobot_view
    response = make_response(robot.get_reply(message))
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/helpers.py", line 191, in make_response
    return current_app.make_response(args)
  File "/root/python/gong_zhong_hao/wxChatBot-main/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'werobot_view' did not return a valid response. The function either returned None or ended without a return statement.
81.69.103.236 - - [12/Dec/2021 19:23:24] "POST /wechat8000?signature=266964ba6e4ed5d33ff4f60391e27fbfd264ac59&timestamp=1639308203&nonce=1288748786&openid=ojhdP5x4fYa9dPDoaANbWz9Nsi-k HTTP/1.1" 500 -

**Comment by bird2426** [comment]
再试试呢，BertTokenizer刚才忘import了😀

**Comment by hobbszhou** [comment]
打扰up了。 我最近才开始搞python，刚刚那个imort的报错问题按道理我应该得看出来的。
这个机器人现在又回到了之前， 一直回 "啊哦，我好像突然傻掉了呢"。 一直都进了 
    if reply[0] != AUDIENCE_MARK:
        reply = [NO_IDEA]
这个if里。
还是不好使

**Comment by bird2426** [comment]
链接：https://pan.baidu.com/s/1YEiC_oI3jlAPbSWqIaHHyw 
提取码：ca6g
不好意思，其实我们的模型还在训练，可能那个不好用，我在readme里面更新了一个模型，因为最近要期末考试了，后续会把代码和模型再重更新整理上传的。
你也可以去看一下gitchat这个项目，我们是在那个基础上训练的。

**Comment by bird2426** [comment]
https://github.com/yangjianxin1/GPT2-chitchat

**Comment by R2D2-3PO** [comment]
lzbnb

**Comment by hobbszhou** [comment]
okok，感谢up。  3q
